version: "3"
services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8200:8200"
  postgresql:
    image: postgres:14
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: postgres
